trigger:
- master

stages:
- stage: Build
  displayName: Build

  jobs:
  - job: RunCMakeTask
    displayName: Run CMake Task

    strategy:
      matrix:
        Linux_Debug:
          OS: 'Linux'
          imageName: 'ubuntu-20.04'
          BuildConfiguration: 'Debug'
          Generator: ''
        Linux_Release:
          OS: 'Linux'
          imageName: 'ubuntu-20.04'
          BuildConfiguration: 'RelWithDebInfo'
          Generator: ''
        MacOS_Debug:
          OS: 'MacOS'
          imageName: 'macos-latest'
          BuildConfiguration: 'Debug'
          Generator: ''
        MacOS_Release:
          OS: 'MacOS'
          imageName: 'macos-latest'
          BuildConfiguration: 'RelWithDebInfo'
          Generator: ''
        Windows_32bit_Debug:
          OS: 'Windows'
          imageName: 'windows-latest'
          BuildConfiguration: 'Debug'
          Generator: '-G "Visual Studio 16 2019" -A Win32'
        Windows_32bit_Release:
          OS: 'Windows'
          imageName: 'windows-latest'
          BuildConfiguration: 'RelWithDebInfo'
          Generator: '-G "Visual Studio 16 2019" -A Win32'
        Windows_64bit_Debug:
          OS: 'Windows'
          imageName: 'windows-latest'
          BuildConfiguration: 'Debug'
          Generator: '-G "Visual Studio 16 2019" -A x64'
        Windows_64bit_Release:
          OS: 'Windows'
          imageName: 'windows-latest'
          BuildConfiguration: 'RelWithDebInfo'
          Generator: '-G "Visual Studio 16 2019" -A x64'

    pool:
      vmImage: $(imageName)

    steps:
    - script: mkdir $(BuildConfiguration)
      displayName: Create Build Directory
      workingDirectory: $(Build.SourcesDirectory)
    - task: CMake@1
      displayName: Generate CMake Cache
      inputs:
        workingDirectory: $(BuildConfiguration)
        cmakeArgs: '-DCMAKE_BUILD_TYPE=$(BuildConfiguration) $(Generator) .. -Dljh_BUILD_TESTS=ON'
    - task: CMake@1
      displayName: Run Build Process
      inputs:
        workingDirectory: $(BuildConfiguration)
        cmakeArgs: '--build . --config $(BuildConfiguration)'
    - script: 'ctest -C $(BuildConfiguration)'
      continueOnError: true
      displayName: Run Tests
      workingDirectory: $(BuildConfiguration)
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFormat: 'cTest'
        testResultsFiles: 'Testing/*/Test.xml'
        failTaskOnFailedTests: true
        configuration: '$(BuildConfiguration)'
        searchFolder: $(BuildConfiguration)